name: Fetch sesam-py and test on PR
on:
  pull_request:
  push:
    branches:
      - playground
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install sesam-py
        run: tag_url=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/sesam-community/sesam-py/releases/latest) && tag=$(basename $tag_url) && filename=sesam-linux-$tag.tar.gz && wget -q https://github.com/sesam-community/sesam-py/releases/download/$tag/$filename && tar -zxf $filename
      - name: Test sesam-py version
        run: ./sesam -version
      - name: Run validation
        run: ./sesam -vv validate